This code is all about pin features functionality
reyven-ai/pintech pull request #12
Opened 2024-02-05 17:54 UTC by reyven-ai

2024-02-06 12:02 UTC, artjom-mashanin reviewed
Damn, that's a big PR :D 

Added some comments

2024-02-06 12:02 UTC, artjom-mashanin commented on frontend/src/components/DropdownUtil/ProfileDropdown.tsx
> +  // }
Do you need this comment?

2024-02-06 12:02 UTC, artjom-mashanin commented on frontend/src/components/Layout/MainHeader.tsx
> +            {/* </li> */}
Do you need these comments?

2024-02-06 12:02 UTC, artjom-mashanin commented on frontend/src/components/pin/Pin.Details.tsx
> +              </button> */}
Do you need these comments?

2024-02-06 12:02 UTC, artjom-mashanin commented on frontend/src/components/pin/Pin.dropzone.tsx
> +// };
Do you need these comments?

2024-02-06 12:02 UTC, artjom-mashanin commented on frontend/src/hooks/useProfileAction.ts
> +// };
Do you need these comments?

2024-02-06 12:02 UTC, artjom-mashanin commented on frontend/src/pages/Profile/Profile.Details.tsx
> +// export default ProfileDetails;
This whole file is commented out 
Do you need it?

2024-02-09 09:10 UTC, reyven-ai commented on dist/index.html
Done!

2024-02-09 09:13 UTC, reyven-ai commented on public/index.html
Done!

2024-02-09 09:18 UTC, reyven-ai commented on frontend/src/components/DropdownUtil/ProfileDropdown.tsx
> +  // }
Done!

2024-02-09 09:18 UTC, reyven-ai commented on frontend/src/components/Layout/MainHeader.tsx
> +            {/* </li> */}
Done!

2024-02-09 09:19 UTC, reyven-ai commented on frontend/src/components/pin/Pin.Details.tsx
> +              </button> */}
Done!

2024-02-09 09:20 UTC, reyven-ai commented on frontend/src/hooks/useProfileAction.ts
> +// };
Done!

2024-02-09 09:21 UTC, reyven-ai commented on frontend/src/components/pin/Pin.dropzone.tsx
> +// };
Done!

2024-02-09 09:21 UTC, reyven-ai commented on frontend/src/pages/Profile/Profile.Details.tsx
> +// export default ProfileDetails;
Done!

2024-02-12 14:01 UTC, artjom-mashanin requested changes

2024-02-16 20:00 UTC, reyven-ai commented on frontend/package.json
> +    "redux-thunk": "^3.1.0",
I just removed them

2024-02-16 20:02 UTC, reyven-ai commented on frontend/src/pages/Profile/Profile.Details.tsx
> +// export default ProfileDetails;
Done!

2024-02-16 20:51 UTC, reyven-ai commented on backend/src/database/migrations/20240208160712_save_pin.ts
> +    table.string("image_url");
Done!

2024-02-16 21:03 UTC, reyven-ai commented on backend/src/modules/profile/profile.services.ts
> +    const getSelfUserProfile = await userRepository.getSelfUserProfile(userId);
Done!

2024-02-17 10:45 UTC, reyven-ai commented on backend/src/modules/profile/profile.services.ts
>      const userRepository = new UserDetailsRepository();
Done!

2024-02-17 13:49 UTC, reyven-ai commented on backend/src/modules/users/users.route.ts
> +        created_by: pin.created_by,
Done!

2024-02-17 13:59 UTC, reyven-ai commented on backend/src/modules/users/users.save.services.ts
> +export async function savePin(data: SavedData): Promise<SavedData | null> {
Done!

2024-02-21 14:57 UTC, reyven-ai commented on frontend/src/validations/pin.validation.ts
> +// The reason I dind't add any validation is because when ever the user is put some unacceptable file or size and trying to sudmit it they will get error from backend valdation and the error will be
I add some image validation for that

2024-02-21 15:16 UTC, reyven-ai commented on backend/src/modules/users/users.route.ts
> +      const userId = req.params.userId;
Done!

2024-02-22 07:19 UTC, artjom-mashanin commented on backend/src/database/migrations/20240104221423_create_users_content.ts
> +    table.string("created_by").references("username").inTable("user_profiles");
You are still changing existing migration — instead create a new migration that changes pins table and adds those new properties

2024-02-22 07:19 UTC, artjom-mashanin commented on backend/src/database/migrations/20240216202000_update_saved_pins.ts
> +  });
Your previous migrattion for rewating the saved pins is not adding these properties anymore — so you don't need to drop the columns in here, cause they technically never existed

You would only ned tyo do that if you have merged the migration to main where you were creating those properties

So technically, you can just remove this migration

2024-02-22 07:19 UTC, artjom-mashanin commented on backend/src/modules/users/users.save.services.ts
> +    const savedPin = await pinRepository.saveUserPin(
I'm curious, what would happen here if you're trying to save a pin that doesn't exist?
Or save it for a user that doesn't exist?

2024-02-24 19:28 UTC, reyven-ai commented on backend/src/database/migrations/20240216202000_update_saved_pins.ts
> +  });
Done!

2024-03-04 21:08 UTC, merged